
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class HomeEntertainment extends javax.swing.JFrame {

    /**
     * Creates new form HomeEntertainment
     */
    public HomeEntertainment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Home Entertainment");

        jButton1.setText("<< Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton2.setText("Home Audio Speakers");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton3.setText("Home Theatres");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton4.setText("Bluetooth Speakers");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton5.setText("DTH Set Top Box");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            File Flipkart = new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment");
            if (Flipkart.exists() && Flipkart.isDirectory()) {
                
            }
            else {
                new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment").mkdir();
            }
            
            FileWriter fw = new FileWriter("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\Home Audio Speakers.doc");
            String loc = "C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\Home Audio Speakers.doc";
            Document doc = Jsoup.connect("https://www.flipkart.com/audio-video/speakers/pr?count=40&otracker=categorytree&p%5B%5D=facets.type%255B%255D%3DHome%2BAudio%2BSpeaker&p%5B%5D=facets.type%255B%255D%3DLaptop%252FDesktop%2BSpeaker&p%5B%5D=facets.type%255B%255D%3DSoundbar&sid=0pm%2F0o7&otracker=nmenu_sub_Electronics_0_Home%20Audio%20Speakers").userAgent("Mozilla/17.0").get();
            Elements temp = doc.select("a._2cLu-l");
            String block;

            int i=0;
            for(Element topic:temp) {
                i++;
                block = topic.getElementsByTag("a").first().text();
                fw.write(i + ": " + block + " \n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null, "File stored at " + loc);  
        }
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            File Flipkart = new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment");
            if (Flipkart.exists() && Flipkart.isDirectory()) {
                
            }
            else {
                new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment").mkdir();
            }
            
            FileWriter fw = new FileWriter("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\Home Theatres.doc");
            String loc = "C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\Home Theatres.doc";
            Document doc = Jsoup.connect("https://www.flipkart.com/home-entertainment/video-players-accessories/home-theaters/pr?sid=ckf%2Csee%2Cmi3&otracker=nmenu_sub_Electronics_0_Home%20Theatres").userAgent("Mozilla/17.0").get();
            Elements temp = doc.select("a._2cLu-l");
            String block;

            int i=0;
            for(Element topic:temp) {
                i++;
                block = topic.getElementsByTag("a").first().text();
                fw.write(i + ": " + block + " \n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null, "File stored at " + loc);  
        }
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            File Flipkart = new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment");
            if (Flipkart.exists() && Flipkart.isDirectory()) {
                
            }
            else {
                new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment").mkdir();
            }
            
            FileWriter fw = new FileWriter("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\Bluetooth Speakers.doc");
            String loc = "C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\Bluetooth Speakers.doc";
            Document doc = Jsoup.connect("https://www.flipkart.com/audio-video/speakers/pr?sid=0pm%2C0o7&otracker=categorytree&p%5B%5D=facets.features%255B%255D%3DBluetooth&otracker=nmenu_sub_Electronics_0_Bluetooth%20Speakers").userAgent("Mozilla/17.0").get();
            Elements temp = doc.select("a._2cLu-l");
            String block;

            int i=0;
            for(Element topic:temp) {
                i++;
                block = topic.getElementsByTag("a").first().text();
                fw.write(i + ": " + block + " \n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null, "File stored at " + loc);  
        }
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            File Flipkart = new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment");
            if (Flipkart.exists() && Flipkart.isDirectory()) {
                
            }
            else {
                new File("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment").mkdir();
            }
            
            FileWriter fw = new FileWriter("C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\DTH Set Top Box.doc");
            String loc = "C:\\Users\\LENOVO\\Desktop\\Flipkart\\Home Entertainment\\DTH Set Top Box.doc";
            Document doc = Jsoup.connect("https://www.flipkart.com/home-entertainment/dth/pr?count=40&otracker=categorytree&p%5B%5D=facets.availability%255B%255D%3DExclude%2BOut%2Bof%2BStock&sid=ckf%2F9wn&otracker=nmenu_sub_Electronics_0_DTH%20Set%20Top%20Box").userAgent("Mozilla/17.0").get();
            Elements temp = doc.select("a._2cLu-l");
            String block;

            int i=0;
            for(Element topic:temp) {
                i++;
                block = topic.getElementsByTag("a").first().text();
                fw.write(i + ": " + block + " \n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null, "File stored at " + loc);  
        }
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeEntertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeEntertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeEntertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeEntertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeEntertainment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
